kind: pipeline
name: default
steps:

  - name: docker-tagged-release
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: quay.io
      repo: quay.io/natlibfi/annif
      tag: [test-tag]
      dry_run: true

trigger:
  branch:
  - master
  - issue297-set-docker-image-tag-from-git-tag
  event:
  - push
