kind: pipeline
name: default
steps:

  - name: docker
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: quay.io
      repo: quay.io/natlibfi/annif
      tags: [latest]

  - name: docker-dev
    image: plugins/docker
    settings:
      dockerfile: Dockerfile-dev
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: quay.io
      repo: quay.io/natlibfi/annif
      tags: [dev]

  trigger:
    branch:
    - master
    event:
    - push
