version: "3"

services:

  bash:
    image: quay.io/natlibfi/annif
    volumes:
      - ${ANNIF_PROJECTS}:/annif-projects
    user: ${MY_UID}:${MY_GID}
    stdin_open: true
    tty: true
    command: bash

  mauiserver:
    image: mauiserver
    volumes:
      - ${ANNIF_PROJECTS}/mauidata:/mauidata
    ports:
      - "8080:8080"
    environment:
      - MY_UID=${MY_UID}
      - MY_GID=${MY_GID}
      - MAUI_SERVER_DATA_DIR=/mauidata

  gunicorn_server:
    image: quay.io/natlibfi/annif
    volumes:
      - ${ANNIF_PROJECTS}:/annif-projects
    user: ${MY_UID}:${MY_GID}
    command: ["gunicorn", "annif:create_app()", "--bind", "0.0.0.0:8000"]

  nginx:
    image: nginx
    volumes:
      - ./annif/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - gunicorn_server
