[tool.poetry]
name = "annif"
version = "0.59.0-dev"
description = "Automated subject indexing and classification tool"
authors = ["National Library of Finland <finto-posti@helsinki.fi>"]
maintainers = [
    "Osma Suominen <osma.suominen@helsinki.fi>",
    "Juho Inkinen <juho.inkinen@helsinki.fi>",
    "Mona Lehtinen <mona.lehtinen@helsinki.fi>",
]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://annif.org"
repository = "https://github.com/NatLibFi/Annif"
documentation = "https://github.com/NatLibFi/Annif/wiki"
keywords = [
    "machine-learning",
    "text-classification",
    "rest-api",
    "code4lib",
    "subject-indexing"
]

classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"

connexion = {version = "2.14.0", extras = ["swagger-ui"]}
swagger_ui_bundle = "0.0.9"
flask = "2.2.2"
flask-cors = "3.0.10"
click = "8.0.4"
click-log = "0.4.0"
joblib = "1.1.0"
nltk = "3.7"
gensim = "4.2.0"
scikit-learn = "1.1.1"
scipy = "1.8.1"
rdflib = "6.2.0"
gunicorn = "20.1.0"
numpy = "1.23.2"
optuna = "2.10.1"
stwfsapy = "0.3.0"
python-dateutil = "2.8.2"
tomli = "2.0.1"
simplemma = "0.7.0"

fasttext = {version = "0.9.2", optional = true}
voikko = {version = "0.5", optional = true}
tensorflow-cpu = {version = "2.9.1", optional = true}
lmdb = {version = "1.3.0", optional = true}
omikuji = {version = "0.5.0", optional = true}
yake = {version = "0.4.5", optional = true}
pycld3 = {version = "0.22", optional = true}
spacy = {version = "3.3.1", optional = true}

[tool.poetry.dev-dependencies]
py = "1.11.0"
pytest = "7.1.2"
requests = "2.28.1"
codecov = "2.1.12"
coverage = "6.2"
pytest-cov = "3.0.0"
pytest-watch = "4.2.0"
pytest-flask = "1.2.0"
pytest-flake8 = "1.1.1"
flake8 = "4.0.1"
bumpversion = "0.6.0"
autopep8 = "1.6.0"

[tool.poetry.extras]
fasttext = ["fasttext"]
voikko = ["voikko"]
nn = ["tensorflow-cpu", "lmdb"]
omikuji = ["omikuji"]
yake = ["yake"]
pycld3 = ["pycld3"]
spacy = ["spacy"]

[tool.poetry.scripts]
annif = "annif.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--flake8"
