name: Prepare
description:
inputs:
  python-version:
    required: true
  poetry-version:
    required: true
runs:
  using: "composite"
  steps:
    - name: Restore cached Poetry installation and its cache
      id: restore-cache
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.cache/pipx/venvs
          ~/.local/bin
          ~/.cache/pypoetry/
        key: poetry-installation-and-cache-${{ inputs.python-version }}-${{ inputs.poetry-version }}-${{ hashFiles('pyproject.toml') }}

    - name: Install Poetry
      shell: bash
      run: |
        pipx install poetry==${{ inputs.poetry-version }}
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@5ccb29d8773c3f3f653e1705f474dfaa8a06a912  # v4.4.0
      with:
        python-version: ${{ inputs.python-version }}
